// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCFh-EVTK-cJUnKlb3qMTihf39eaK33Tw',
    appId: '1:640293520486:web:85ce21520d794b890b99a7',
    messagingSenderId: '640293520486',
    projectId: 'digital-time-capsule-app',
    authDomain: 'digital-time-capsule-app.firebaseapp.com',
    storageBucket: 'digital-time-capsule-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTOIGpt6cedUfyzRuNv1v4WYluIyaYBwQ',
    appId: '1:640293520486:android:7a8340335b8fade80b99a7',
    messagingSenderId: '640293520486',
    projectId: 'digital-time-capsule-app',
    storageBucket: 'digital-time-capsule-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHCKDzI_7PZtCbC-osBvp7SHCuc0OGLvY',
    appId: '1:640293520486:ios:1ac0f67cc34684780b99a7',
    messagingSenderId: '640293520486',
    projectId: 'digital-time-capsule-app',
    storageBucket: 'digital-time-capsule-app.firebasestorage.app',
    iosBundleId: 'com.digitaltimecapsule.digitalTimeCapsule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCFh-EVTK-cJUnKlb3qMTihf39eaK33Tw',
    appId: '1:640293520486:web:16e97b6aaf2db7cc0b99a7',
    messagingSenderId: '640293520486',
    projectId: 'digital-time-capsule-app',
    authDomain: 'digital-time-capsule-app.firebaseapp.com',
    storageBucket: 'digital-time-capsule-app.firebasestorage.app',
  );

}